/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hdq' at '17-5-30 下午4:57' with Gradle 2.11
 *
 * @author hdq, @date 17-5-30 下午4:57
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
